# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3307/punto_facil
spring.datasource.username=root
spring.datasource.password=yeahbaby
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Ajustes optimizados para evitar "Connection closed"
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.validation-timeout=3000